//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rasxod.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expnss
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int NameExp { get; set; }
        public decimal Summ { get; set; }
        public System.DateTime DateExps { get; set; }
        public string Description { get; set; }
    
        public virtual NameExp NameExp1 { get; set; }
        public virtual Users Users { get; set; }
    }
}
